version: '3.8'

services:
  postgresql_db_technical_test:
    image: postgres:alpine
    container_name: technical_test_db

    ports:
      - 5432:5432

    volumes:
      - felipe_technical_test_dbdata:/var/lib/postgresql/data

    env_file:
      - .env

    restart: always

volumes:
  felipe_technical_test_dbdata:
